console/groups/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('groups.views',
                       (r'^$',            'index_req'),
                       (r'^search$',      'search_req'),
                       (r'^group$',       'group_req'),
                       (r'^remove_from_group$', 'remove_from_group_req'),
		       (r'^wiz_create$',  'wiz_create_req'),
		       (r'^wiz_name$',    'wiz_name_req'),
		       (r'^wiz_users$',   'wiz_users_req'),
		       (r'^add_user$',    'add_user_req'),
		       (r'^delete$',      'delete_req'),
		       (r'^delete_wl_entry$', 'delete_wl_entry_req'),
		       (r'^edit$',        'edit_req'),
                       )

console/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
                       (r'^$', 'views.index_req'),
		       (r'^console-led\.png$', 'views.console_led_req'),
		       (r'^db-led\.png$', 'views.db_led_req'),
		       (r'^gateway-led\.png$', 'views.gateway_led_req'),
		       (r'^mclocals-led\.png$', 'views.mclocals_led_req'),

                       (r'^admins/', include('admins.urls')),
                       (r'^users/', include('users.urls')),
                       (r'^groups/', include('groups.urls')),
                       (r'^idps/', include('idps.urls')),
                       (r'^logs/', include('logs.urls')),

                       (r'^account/', include('account.urls')),
		       (r'^config/',  include('config.urls')),
                       (r'^backups/', include('backups.urls')),
		       (r'^security/', include('security.urls')),
		       (r'^appliances/', include('appliances.urls')),
		       (r'^applications/', include('applications.urls')),
		       (r'^demos/', include('demos.urls')),

                       (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                        {'document_root': settings.INSTALL_DIR + 'media/'}),


                       # Uncomment this for admin:
                       (r'^admin/', include('django.contrib.admin.urls')),
)

console/users/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('users.views',
                       (r'^$',         'index_req'),
                       (r'^search$',   'search_req'),
                       (r'^user$',     'user_req'),
                       (r'^password$', 'password_req'),
                       (r'^create$',   'create_req'),
                       (r'^disable$',  'disable_req'),
                       (r'^claim$',    'claim_req'),
                       (r'^edit$',     'edit_req'),
                       (r'^groups$',   'groups_req'),
                       (r'^addgroup$', 'addgroup_req'),
                       (r'^add_to_group$', 'add_to_group_req'),
                       (r'^remove_from_group$', 'remove_from_group_req'),
                       (r'^unlink_idp$', 'unlink_idp_req'),
                       (r'^login_as$', 'login_as_req'),
                       )

console/users/models.py
#!/usr/bin/env python

from django.db import models
from django.db.models import Q

import re
from sha import sha

# 4 groups of 4 digits, optionally separated by space, tab, period, or dash
VALID_MCID = '^[0-9]{4}([\. \t-]?[0-9]{4}){3}$'

delimiters = re.compile('[\. \t-]')
valid_mcid = re.compile(VALID_MCID)

def all_query_set(order_by = ('-since',)):
    return User.objects.exclude(acctype='DISABLED').order_by(*order_by)

def search_query_set(qstr, order_by=('-since',)):
    qstr = qstr.strip()
    qs = User.objects

    for q in qstr.split():
        if '@' in q:
            qs = qs.filter(email=q)

        elif is_mcid(q):
            qs = qs.filter(mcid=normalize_mcid(q))

        else:
            qs = qs.filter(Q(first_name=q) | Q(last_name=q))

    return qs.order_by(*order_by)

ACCTYPE_CHOICES = [
	('USER',	'User'),
	('GROUP',	'Group'),
	('SPONSORED',	'Sponsored'),
	('CLAIMED',	'Claimed'),
	('UNVALIDATED',	'Unvalidated'),
	('TEMPORARY',	'Temporary'),
	('EXPIRED',	'Expired'),
        ('DISABLED',    'Disabled')]

class User(models.Model):
    mcid = models.CharField(maxlength = 16,
                            primary_key=True)

    email = models.CharField(null=True, blank=True, maxlength=192,
			     db_index=True, unique=True)

    sha1 = models.CharField(null=True, blank=True, maxlength=120)

    since = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(blank=True, maxlength=96)
    last_name = models.CharField(blank=True, maxlength=96)
    mobile = models.CharField(blank=True, maxlength=192)
    smslogin = models.IntegerField(null=True, blank=True)
    updatetime = models.IntegerField()
    ccrlogupdatetime = models.IntegerField()
    chargeclass = models.CharField(blank=True, maxlength=765)
    rolehack = models.CharField(blank=True, maxlength=765)
    affiliationgroupid = models.IntegerField(null=True, blank=True)
    startparams = models.CharField(blank=True, maxlength=765)
    stylesheetUrl = models.CharField(blank=True, maxlength=765)
    picslayout = models.CharField(blank=True, maxlength=765)
    photoUrl = models.CharField(blank=True, maxlength=765)
    acctype = models.CharField(choices = ACCTYPE_CHOICES,
			       blank = True, maxlength = 255,
			       default = 'USER')

    def claimable(self):
        return self.acctype in ['DISABLED', 'SPONSORED', 'CLAIMED']

    persona = models.CharField(blank=True, maxlength=765)
    validparams = models.CharField(blank=True, maxlength=765)
    interests = models.CharField(blank=True, maxlength=765)
    email_verified = models.DateTimeField(null=True, blank=True)
    mobile_verified = models.DateTimeField(null=True, blank=True)

    # binary data
    enc_skey = models.CharField(blank=True, maxlength=12)

    enable_simtrak = models.BooleanField()
    enable_dod = models.BooleanField()

    def set_password(self, pw):
        sha1 = sha('medcommons.net')
        sha1.update(str(self.mcid))
        sha1.update(pw)
        self.sha1 = sha1.hexdigest().upper()

    def pretty_mcid(self):
        return pretty_mcid(self.mcid)

    class Meta:
        db_table = 'users'

    class Admin:
        pass

def normalize_mcid(mcid):
    """Remove common punctuation from a user-entered MCID.

    Examples:
    >>> normalize_mcid('0123456789012345')
    '0123456789012345'

    >>> normalize_mcid('0123 4567 8901 2345')
    '0123456789012345'

    >>> normalize_mcid('0123-4567-8901-2345')
    '0123456789012345'
    """
    if isinstance(mcid, User):
        mcid = mcid.mcid
    else:
        mcid = ''.join(delimiters.split(str(mcid)))

    return ('0000000000000000' + mcid)[-16:]

def pretty_mcid(mcid):
    """
    pre: len(mcid) == 16
    post: ''.join(__return__.split('-')) == mcid
    """
    mcid = normalize_mcid(mcid)
    return "%s-%s-%s-%s" % (mcid[0:4], mcid[4:8], mcid[8:12], mcid[12:16])

def is_mcid(mcid):
    """Tests if an MCID is a valid 16-digit number.

    >>> is_mcid('test')
    False

    >>> is_mcid('012345')
    False

    >>> is_mcid('this is 16 chars')
    False

    >>> is_mcid('0123456789012345')
    True

    >>> is_mcid('0123-4567-8901-2345')
    True
    """
    return bool(valid_mcid.match(mcid))

console/groups/views.py
#!/usr/bin/env python
# vim: tabstop=8 softtabstop=8 shiftwidth=8 expandtab

from django import newforms as forms # change to 'from django import forms'
from django.http import HttpResponseRedirect
from django.views.generic.list_detail import object_list
from django.shortcuts import render_to_response

from groups.models import Group, Practice, create_group, delete_group, \
			  Practiceccrevent

from users.models import User, VALID_MCID, pretty_mcid, \
			 normalize_mcid, search_query_set, all_query_set

from utils import login_required, sql_execute, submit_redirect, \
                          default_context

@login_required
def index_req(request):
    return object_list(request,
                       queryset = Group.objects.order_by('name'),
                       template_name = 'groups/index.html',
                       paginate_by = 20,
                       allow_empty = True,
                       extra_context = default_context(request))

@login_required
def search_req(request):
    q = request.GET['q']
    qs = Group.objects.filter(name__icontains = q)
    
    return object_list(request,
                       queryset = qs,
                       template_name = 'groups/search.html',
                       paginate_by = 20,
                       allow_empty = True,
                       extra_context = default_context(request, q=q))

@login_required
def group_req(request):
    try:
        id = int(request.GET['id'])
        group = Group.objects.get(groupinstanceid=id)

        where = ['groupmembers.memberaccid = users.mcid',
                 'groupmembers.groupinstanceid = groupinstances.groupinstanceid',
                 'groupinstances.groupinstanceid = %d' % id]

        admin_where = ['groupadmins.adminaccid = users.mcid',
                       'groupadmins.groupinstanceid = groupinstances.groupinstanceid',
                       'groupinstances.groupinstanceid = %d' % id]
	try:
	    practice = Practice.objects.get(providergroupid = id)
	    worklist = Practiceccrevent.objects.filter(practiceid = practice.practiceid, ViewStatus='VISIBLE')
	except Practice.DoesNotExist:
	    practice = None
	    worklist = []

        users = User.objects.extra(where=where,
                                   tables = ['groupmembers', 'groupinstances'])

        owners = User.objects.extra(where=admin_where,
                                   tables = ['groupadmins', 'groupinstances'])

        owner = None
        if(len(owners)>0):
                owner = owners[0]

        return render_to_response('groups/group.html',
                                  default_context(request, group=group,
			                          practice = practice,
			                          worklist = worklist,
                                                  users = users,
                                                  owner = owner))
    except KeyError:
        return render_to_response('groups/query.html',
                                  default_context(request))

@login_required
def delete_wl_entry_req(request):
    pid = int(request.REQUEST['pid'])

    practice = Practice.objects.get(practiceid = pid)

    if request.POST:
	guid = request.POST['guid']

	if 'delete' in request.POST or 'delete.x' in request.POST:
	    sql_execute("DELETE FROM practiceccrevents WHERE Guid=%s AND practiceid=%s",
			guid, pid)
	return HttpResponseRedirect('group?id=%d' % practice.providergroupid.groupinstanceid)

    guid = request.GET['guid']
    event = Practiceccrevent.objects.get(Guid=guid, practiceid=pid)

    return render_to_response('groups/delete_wl_entry.html',
                              default_context(request, entry=entry,
                                              practice=practice))

@login_required
def remove_from_group_req(request):
    mcid = request.REQUEST['mcid']
    group = request.REQUEST['group']

    if 'delete' in request.POST or 'delete.x' in request.POST:
	sql_execute("DELETE FROM groupmembers " + \
	            "WHERE groupinstanceid=%s AND memberaccid=%s;",
	            int(group), mcid)

    return HttpResponseRedirect("group?id=" + group)

class CreateForm(forms.Form):
    owner_mcid = forms.RegexField(VALID_MCID)
    id = forms.CharField(widget = forms.HiddenInput(),
                         required = False)

@login_required
def wiz_create_req(request):
    id = request.REQUEST.get('id', '')
    action = 'wiz_create?id=%s' % id

    if id:
        g = Group.objects.get(groupinstanceid = id)
    else:
        g = None

    queryset = all_query_set()

    if 'search' in request.POST or 'search.x' in request.POST:
        queryset = search_query_set(request.POST['q'])
        form = CreateForm(initial = request.POST)

    elif request.POST:
        form = CreateForm(request.POST)

        if form.is_valid():
            mcid = normalize_mcid(form.clean_data['owner_mcid'])

            if g:
                p = Practice.objects.get(practiceid = g.parentid)
                p.accid_id = g.accid_id = mcid

                p.save()
            else:
                g = create_group('New Group', mcid,
                                 'https://' + request.META['SERVER_NAME'])

            g.save()

    	    return HttpResponseRedirect('wiz_name?id=%d' % g.groupinstanceid)
    else:
        initial = dict(id = id)

        if 'mcid' in request.REQUEST:
            initial['owner_mcid'] = pretty_mcid(request.REQUEST['mcid'])
	elif g:
	    initial['owner_mcid'] = pretty_mcid(g.accid_id)

        form = CreateForm(initial = initial)

    return object_list(request, queryset = queryset,
                       template_name = 'groups/wiz_1create.html',
                       paginate_by = 20,
                       extra_context = default_context(request,
                                                       form=form,
                                                       action=action))

class CreateNameForm(forms.Form):
    name = forms.CharField()
    id = forms.CharField(widget = forms.HiddenInput())
    
@login_required
def wiz_name_req(request):
    id = request.REQUEST['id']
    g = Group.objects.get(groupinstanceid = id)

    if request.POST:
        form = CreateNameForm(request.POST)

        if form.is_valid():
            p = Practice.objects.get(practiceid = g.parentid)
            g.name = p.practicename = form.clean_data['name']

            g.save()
            p.save()

            if 'prev' in request.POST:
                url = 'wiz_create?id=%d&mcid=%s' % (g.groupinstanceid, g.accid.mcid)
            else:
                url = 'wiz_users?id=%d' % g.groupinstanceid

            return HttpResponseRedirect(url)

    else:
        form = CreateNameForm(dict(name = g.name,
                                id = g.groupinstanceid))

    return render_to_response('groups/wiz_2name.html',
                              default_context(request, form=form, id=id))

@login_required
def wiz_users_req(request):
    id = request.REQUEST['id']

    return add_users(request,
		     this_action = 'wiz_users?id=%s' % id,
		     next_action = '.',
		     template = 'groups/wiz_3users.html')

@login_required
def add_user_req(request):
    id = request.REQUEST['id']
    action = 'add_user?id=%s' % id

    return add_users(request,
		     this_action = 'add_user?id=%s' % id,
		     next_action = 'group?id=%s' % id,
		     template='groups/adduser.html')

def add_users(request, this_action, next_action, template):
    id = request.REQUEST['id'].strip()
    group = Group.objects.get(groupinstanceid=int(id))

    context = default_context(request, action=this_action, group=group, id=id)

    if 'q' in request.REQUEST:
	q = request.REQUEST['q']
	qs = search_query_set(q)
	context['q'] = q
    else:
	qs = all_query_set()

    if 'mcid' in request.POST:
        mcid = normalize_mcid(request.POST['mcid'])

        if 'remove.x' in request.POST:
            sql_execute("DELETE FROM groupmembers " + \
                        "WHERE groupinstanceid = %s AND memberaccid = %s",
                        int(id), mcid)
        elif 'add.x' in request.POST:
	    # Only one group per user
	    sql_execute("DELETE FROM groupmembers " + \
			"wHERE memberaccid = %s", mcid)

            sql_execute("INSERT INTO groupmembers " + \
                        "(groupinstanceid, memberaccid) " + \
                        "VALUES (%s, %s)", int(id), mcid)

        return HttpResponseRedirect(this_action)

    if 'prev' in request.POST:
        return HttpResponseRedirect('wiz_name?id=%s' % id)

    if 'finish' in request.POST:
        return HttpResponseRedirect(next_action)

    where = ['groupmembers.memberaccid = users.mcid',
             'groupmembers.groupinstanceid = %s' % id]
    context['members'] = User.objects.extra(where = where,
                                            tables = ['groupmembers'])

    where = ['mcid NOT IN (SELECT memberaccid FROM groupmembers WHERE groupinstanceid = %s)' % id]
    select = {'groupname': 'SELECT DISTINCT(name) FROM groupinstances, groupmembers WHERE groupmembers.groupinstanceid = groupinstances.groupinstanceid AND groupmembers.memberaccid = users.mcid'}

    return object_list(request,
                       queryset = qs.extra(where = where,
					   select = select),
                       template_name = template,
                       paginate_by = 20,
                       extra_context = context)

@login_required
def delete_req(request):
    if request.POST:
	if 'delete' in request.POST or 'delete.x' in request.POST:
	    id = request.POST['id']
	    group = Group.objects.get(groupinstanceid = id)
	    delete_group(group)

	return HttpResponseRedirect('.')

    id = request.GET['id']
    group = Group.objects.get(groupinstanceid=id)

    where = ['groupmembers.memberaccid = users.mcid',
             'groupmembers.groupinstanceid = groupinstances.groupinstanceid',
             'groupinstances.groupinstanceid = %s' % id]

    users = User.objects.extra(where=where,

console/templates/users/addgroup.html
{% extends "form.html" %}

{% block title %}Add Group{% endblock %}

{% block breadcrumbs %}
<a href='..'>Home</a> &gt;
<a href='.'>Accounts</a> &gt;
<a href='user?mcid={{ mcuser.mcid }}'>{{ mcuser.pretty_mcid }}</a> &gt;
Add Group
{% endblock %}

{% block content %}

{% if form.errors %}
<h2>Please correct the following error{{ form.errors|pluralize }}:</h2>
{% endif %}

<form action='addgroup' method='post'>
  <input type='hidden' name='mcid' value='{{ mcuser.mcid }}' />

  <table>
    <tbody>
{{ form }}
    </tbody>
  </table>

  <div id='submit-row'>
    <input type='submit'
	   value='Save' class='default' />

    <input type='submit'
	   name='add'
	   value='Save and add another' />

    <input type='submit'
	   name='edit'
	   value='Save and continue editing' />
  </div>
</form>

{% endblock %}

console/templates/users/claim.html
{% extends "form.html" %}

{% block title %}Claim Account{% endblock %}

{% block breadcrumbs %}
<a href='..'>Home</a> &gt;
<a href='.'>Accounts</a> &gt;
Claim Account {{ mcuser.pretty_mcid }} ({{ mcuser.first_name }} {{ mcuser.last_name }})
{% endblock %}

{% block content %}

<p>
A person must verify his/her identity with you
before you release this password.
</p>

{% if form.errors %}
<h2>Please correct the following error{{ form.errors|pluralize }}:</h2>
{% endif %}

<form method='post'
      action='claim'>

  <table>
    <tbody>
      <tr>
        <th><label for='id_mcid'>MCID:</label></th>
	<td><input type='text' readonly='readonly' name='mcid' id='id_mcid'
	           value='{{ mcuser.pretty_mcid }}' /></td>
      </tr>
{{ form }}
      <tr>
	<td></td>
	<td>
<a href='claim?mcid={{ mcuser.mcid }}'>new random password</a>
	</td>
      </tr>
    </tbody>
  </table>

  <div id='submit-row'>
    <input type='submit' value='Claim' class='default' />
  </div>
</form>

{% endblock %}

console/templates/users/create.html
{% extends "form.html" %}

{% load medcommons %}

{% block title %}Create Account{% endblock %}

{% block breadcrumbs %}
<a href='..'>Home</a> &gt;
<a href='.'>Accounts</a> &gt;
Create Account
{% endblock %}

{% block content %}

{% if form.errors %}
<h2>Please correct the following error{{ form.errors|pluralize }}:</h2>
{% endif %}

<form method='post'
      action='create'>

  <table>
    <tbody>
      <tr>
	<th><label for='id_mcid'>MCID:</label></th>
	<td>
	  <input type='text' readonly='readonly'
	         name='mcid' id='id_mcid' value='{{ mcid|mcid }}' />
	</td>
      </tr>

{{ form }}
    </tbody>
  </table>

  <div id='submit-row'>
    <input type='submit' value='Save' class='default' />

    <input type='submit'
	   name='create'
	   value='Save and create another' />

    <input type='submit'
	   name='edit'
	   value='Save and continue editing' />

  </div>
</form>

{% endblock %}

console/templates/users/edit.html
{% extends "form.html" %}

{% block title %}Edit Account{% endblock %}

{% block breadcrumbs %}
<a href='..'>Home</a> &gt;
<a href='.'>Accounts</a> &gt;
Edit {{ mcuser.pretty_mcid }} {{ mcuser.first_name }} {{ mcuser.last_name }}
{% endblock %}

{% block sidebar %}
<ul class='object-tools'>
{% include "users/tools.inc" %}
  <li><a href='user?mcid={{ mcuser.mcid }}'>View Account</a></li>
</ul>
{% endblock %}

{% block content %}

{% if form.errors %}
<h2>Please correct the following error{{ form.errors|pluralize }}:</h2>
{% endif %}

<form method='post'
      action='edit'>

  <table>
    <tbody>
      <tr>
        <th><label for='id_mcid'>MCID:</label></th>
	<td><input type='text' readonly='readonly' name='mcid' id='id_mcid'
	           value='{{ mcuser.pretty_mcid }}' /></td>
      </tr>
{{ form }}
    </tbody>
  </table>

  <div id='submit-row'>
    <input type='submit' value='Save' class='default' />

    <input type='submit'
	   name='create'
	   value='Save and create another' />

    <input type='submit'
	   name='edit'
	   value='Save and continue editing' />
  </div>
</form>

{% endblock %}

console/templates/users/index.html
{% extends "base.html" %}

{% load medcommons %}

{% block title %}Account List{% endblock %}

{% block sidebar %}
<ul class='object-tools'>
  <li><a href='create' class='addlink'>Create Account</a></li>
</ul>
{% endblock sidebar %}

{% block breadcrumbs %}
<a href='..'>Home</a> &gt;
Accounts
{% endblock %}

{% block content %}

<table>
  <thead>
    <tr>
      <td></td>
      <td>
	<a href='{{ order_query }}order=mcid'>
	  <img src='{{ media }}img/up.png' width='5' height='4'
	       alt='Sort by MCID (increasing)' />
	</a>
	MCID
	<a href='{{ order_query }}order=-mcid'>
	  <img src='{{ media }}img/dn.png' widht='5' height='4'
	       alt='Sort by MCID (decreasing)' />
	</a>
      </td>
      <td>
	<a href='{{ order_query }}order=last_name,first_name'>
	  <img src='{{ media }}img/up.png' width='5' height='4'
	       alt='Sort by Name (increasing)' />
	</a>
	Name
	<a href='{{ order_query }}order=-last_name,-first_name'>
	  <img src='{{ media }}img/dn.png' width='5' height='4'
	       alt='Sort by Name (decreasing)' />
	</a>
      </td>
      <td>
	<a href='{{ order_query }}order=email'>
	  <img src='{{ media }}img/up.png' width='5' height='4'
	       alt='Sort by Email (increasing)' />
	</a>
	Email
	<a href='{{ order_query }}order=-email'>
	  <img src='{{ media }}img/dn.png' width='5' height='4'
	       alt='Sort by Email (decreasing)' />
	</a>
      </td>
      <td>Status</td>
      <td>
    <a href='{{ order_query }}order=since'>
      <img src='{{ media }}img/up.png' width='5' height='4'
           alt='Sort by Account Created (increasing)' />
    </a>
    Account Created
    <a href='{{ order_query }}order=-since'>
      <img src='{{ media }}img/dn.png' width='5' height='4'
           alt='Sort by Account Created (decreasing)' />
    </a>
      </td>
      <td>
    <a href='{{ order_query }}order=ccrlogupdatetime'>
      <img src='{{ media }}img/up.png' width='5' height='4'
           alt='Sort by Update Time (increasing)' />
    </a>
    CCR Log Updated
    <a href='{{ order_query }}order=-ccrlogupdatetime'>
      <img src='{{ media }}img/dn.png' width='5' height='4'
           alt='Sort by Update Time (decreasing)' />
    </a>
      </td>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <td colspan='7'>
	<span style='float: left'>
{% if has_previous %}
<a href='{{ search_query }}page=1'>&laquo; first</a>
<a href='{{ search_query }}page={{ previous }}'>&lt; prev</a>
{% endif %}
	</span>
	<span style='float: right'>
{% if has_next %}
<a href='{{ search_query }}page={{ next }}'>next &gt;</a>
<a href='{{ search_query }}page={{ pages }}'>last &raquo;</a>
{% endif %}
	</span>
      </td>
    </tr>
    <tr>
      <td colspan='7'>
	<span style='float: left'>
	  <a href='create'>
	    <img src='{{ media }}img/CreateUser.png' width='20' height='20'
		 alt='Create Account' />
	    create account
	  </a>
	</span>
	<span style='float: right'>
Page {{ page }} of {{ pages }}.
	</span>
      </td>
    </tr>
    <tr>
      <td colspan='7'>
<form method='get' action='search'>
  <label>Search Accounts:
    <input type='text' name='q' value='{{ q }}' size='30' /></label>
  <input type='image' src='{{ media }}img/icon_searchbox.png' width='18' height='16'
         name='search' alt='Search Accounts' />
</form>
      </td>
    </tr>
  </tfoot>

  <tbody>
{% for entry in object_list %}
    <tr class='{% cycle a,b %}'>
      <td>
        <a href='edit?mcid={{ entry.mcid }}'>
	  <img src='{{ media }}img/icon_changelink.gif' width='10' height='10'
	       alt='Edit account' />
	</a>
	<a href='disable?mcid={{ entry.mcid }}'>
	  <img src='{{ media }}img/icon_deletelink.gif' width='10' height='10'
	       alt='Disable account' />
	</a>
      </td>
      <td>
        <a href='user?mcid={{ entry.mcid }}'>{{ entry.pretty_mcid }} </a>
      </td>
      <td>{{ entry.first_name }} {{ entry.last_name }}</td>
      <td><a href='search?q={{ entry.email }}'>{{ entry.email }}</a></td>
      <td>{{ entry.get_acctype_display }}</td>
      <td>{{ entry.since }}</td>
      <td>{{ entry.ccrlogupdatetime|timestamp }}</td>
    </tr>
{% endfor %}
  </tbody>
</table>

{% endblock %}

console/templates/users/login_as.html
{% extends "form.html" %}

{% block title %}Login As Account{% endblock %}

{% block breadcrumbs %}
<a href='..'>Home</a> &gt;
<a href='.'>Accounts</a> &gt;
Login As {{ mcuser.pretty_mcid }} {{ mcuser.first_name }} {{ mcuser.last_name }}
{% endblock %}

{% block sidebar %}
<ul class='object-tools'>
{% include "users/tools.inc" %}
  <li><a href='user?mcid={{ mcuser.mcid }}'>View Account</a></li>
</ul>
{% endblock %}

{% block content %}
<p>
Please login again,  using <strong>your</strong>
console username.
</p>
<form method='post'
      action='https://{{ META.SERVER_NAME }}/acct/console.php'>
  <table>
    <tr>
      <td><label for='user'>&nbsp;</label></td>
      <td>
  <input type='text'
         readonly='readonly'
         name='user'
         value='{{ user }}' />
      </td>
    </tr>
    <tr>
      <td><label for='mcid'>MCID</label></td>
      <td>
  <input type='text'
         name='mcid'
         readonly='readonly'
         value='{{ mcid }}' />
      </td>
    </tr>
    <tr>
      <td><label for='password'>Password</label></td>
      <td>
  <input type='password'
         name='password' />
      </td>
    </tr>
  </table>

  <div id='submit-row'>
<input type='submit'
       class='default'
       value='Sign On' />
  </div>
</form>

{% endblock %}